FROM openjdk:8-jre-alpine

ENV TZ=Asia/Shanghai \
    LANG=en_US.UTF-8  \
    LC_ALL=en_US.UTF8
    
RUN apk update && \
    apk add --no-cache bash tzdata && \
    addgroup -S work && adduser -S -G work work -s /bin/bash && \
    rm -rf /var/cache/apk/* /tmp/* /var/tmp/* $HOME/.cache