FROM alpine

# httptool ab wrk c1000k(test socket)
RUN apk update && \
    apk add vim iproute2 curl apache2-utils wrk make gcc libc-dev busybox-extras && \
    wget --no-check-certificate https://github.com/ideawu/c1000k/archive/master.zip && \
    unzip master.zip && \ 
    cd c1000k-master && \
    make && \
    rm -rf /var/cache/apk/*
